INSERT INTO "tb_estoque"("id", "item", "quantidadeestoque", "unidade", "fk_departamento", "codigoean") VALUES (6, 'Tonner Amarelo', 50, 'UN', 2, '123456787');
INSERT INTO "tb_estoque"("id", "item", "quantidadeestoque", "unidade", "fk_departamento", "codigoean") VALUES (7, 'Tonner Preto', 50, 'UN', 2, '123465786');
INSERT INTO "tb_estoque"("id", "item", "quantidadeestoque", "unidade", "fk_departamento", "codigoean") VALUES (14, 'RJ 45', 100, 'UN', 2, '123456784');
INSERT INTO "tb_estoque"("id", "item", "quantidadeestoque", "unidade", "fk_departamento", "codigoean") VALUES (15, 'Fio elétrico flexível 2mm', 200, 'MTS', 4, '123456783');
INSERT INTO "tb_estoque"("id", "item", "quantidadeestoque", "unidade", "fk_departamento", "codigoean") VALUES (16, 'Fio elétrico flexível 6mm', 200, 'MTS', 4, '123456782');
INSERT INTO "tb_estoque"("id", "item", "quantidadeestoque", "unidade", "fk_departamento", "codigoean") VALUES (17, 'Cabo CAT 4', 200, 'MTS', 2, '123456781');
INSERT INTO "tb_estoque"("id", "item", "quantidadeestoque", "unidade", "fk_departamento", "codigoean") VALUES (18, 'Cabo CAT 6', 200, 'MTS', 2, '123456780');
INSERT INTO "tb_estoque"("id", "item", "quantidadeestoque", "unidade", "fk_departamento", "codigoean") VALUES (12, 'Telefone com Fio', 8, 'UN', 5, '987654321');
INSERT INTO "tb_estoque"("id", "item", "quantidadeestoque", "unidade", "fk_departamento", "codigoean") VALUES (13, 'RJ 11', 99, 'UN', 5, '987654320');
INSERT INTO "tb_estoque"("id", "item", "quantidadeestoque", "unidade", "fk_departamento", "codigoean") VALUES (19, 'Cabo Telefone', 199, 'MTS', 5, '159789623');
INSERT INTO "tb_estoque"("id", "item", "quantidadeestoque", "unidade", "fk_departamento", "codigoean") VALUES (8, 'Areia', 49, 'KG', 1, '446585142');
INSERT INTO "tb_estoque"("id", "item", "quantidadeestoque", "unidade", "fk_departamento", "codigoean") VALUES (9, 'Pedra', 49, 'KG', 1, '254785279');
INSERT INTO "tb_estoque"("id", "item", "quantidadeestoque", "unidade", "fk_departamento", "codigoean") VALUES (2, 'Parafuso Fenda 2mm', 298, 'UN', 4, '165748978');
INSERT INTO "tb_estoque"("id", "item", "quantidadeestoque", "unidade", "fk_departamento", "codigoean") VALUES (3, 'Lampada 100w', 15, 'UN', 4, '484258069');
INSERT INTO "tb_estoque"("id", "item", "quantidadeestoque", "unidade", "fk_departamento", "codigoean") VALUES (21, 'Monitor 23 pol', 0, 'UN', 2, '804654600');
INSERT INTO "tb_estoque"("id", "item", "quantidadeestoque", "unidade", "fk_departamento", "codigoean") VALUES (20, 'Monitor 21 pol', 2, 'UN', 2, '184897989');
INSERT INTO "tb_estoque"("id", "item", "quantidadeestoque", "unidade", "fk_departamento", "codigoean") VALUES (22, 'Monitor 17 pol', 0, 'UN', 2, '650416501');
INSERT INTO "tb_estoque"("id", "item", "quantidadeestoque", "unidade", "fk_departamento", "codigoean") VALUES (1, 'Cimento', 200, 'KG', 1, '245678225');
INSERT INTO "tb_estoque"("id", "item", "quantidadeestoque", "unidade", "fk_departamento", "codigoean") VALUES (5, 'Tonner Ciano', 47, 'UN', 2, '123456788');
INSERT INTO "tb_estoque"("id", "item", "quantidadeestoque", "unidade", "fk_departamento", "codigoean") VALUES (4, 'Tonner Magenta', 49, 'UN', 2, '123456789');
INSERT INTO "tb_estoque"("id", "item", "quantidadeestoque", "unidade", "fk_departamento", "codigoean") VALUES (11, 'Telefone sem fio', 8, 'UN', 5, '987654322');
INSERT INTO "tb_estoque"("id", "item", "quantidadeestoque", "unidade", "fk_departamento", "codigoean") VALUES (10, 'Lamina de Corte', 16, 'UN', 1, '123456785');
