INSERT INTO "tb_itemservico"("id", "itemservico", "vinculoestoque", "fk_departamento") VALUES (1, 'Fazer parede', NULL, 1);
INSERT INTO "tb_itemservico"("id", "itemservico", "vinculoestoque", "fk_departamento") VALUES (2, 'Fazer massa ', NULL, 1);
INSERT INTO "tb_itemservico"("id", "itemservico", "vinculoestoque", "fk_departamento") VALUES (3, 'Concretar pilar', NULL, 1);
INSERT INTO "tb_itemservico"("id", "itemservico", "vinculoestoque", "fk_departamento") VALUES (4, 'Concretar viga', NULL, 1);
INSERT INTO "tb_itemservico"("id", "itemservico", "vinculoestoque", "fk_departamento") VALUES (5, 'Cimentar Chão', NULL, 1);
INSERT INTO "tb_itemservico"("id", "itemservico", "vinculoestoque", "fk_departamento") VALUES (6, 'Fazer Concreto', NULL, 1);
INSERT INTO "tb_itemservico"("id", "itemservico", "vinculoestoque", "fk_departamento") VALUES (7, 'Preparar Argamassa', NULL, 1);
INSERT INTO "tb_itemservico"("id", "itemservico", "vinculoestoque", "fk_departamento") VALUES (8, 'Rebocar', NULL, 1);
INSERT INTO "tb_itemservico"("id", "itemservico", "vinculoestoque", "fk_departamento") VALUES (9, 'Chapiscar', NULL, 1);
INSERT INTO "tb_itemservico"("id", "itemservico", "vinculoestoque", "fk_departamento") VALUES (10, 'Trocar Monitor', NULL, 2);
INSERT INTO "tb_itemservico"("id", "itemservico", "vinculoestoque", "fk_departamento") VALUES (11, 'Trocar Mouse', NULL, 2);
INSERT INTO "tb_itemservico"("id", "itemservico", "vinculoestoque", "fk_departamento") VALUES (12, 'Trocar Teclado', NULL, 2);
INSERT INTO "tb_itemservico"("id", "itemservico", "vinculoestoque", "fk_departamento") VALUES (13, 'Trocar Tonner', NULL, 2);
INSERT INTO "tb_itemservico"("id", "itemservico", "vinculoestoque", "fk_departamento") VALUES (14, 'Limpar Gabinete', NULL, 2);
INSERT INTO "tb_itemservico"("id", "itemservico", "vinculoestoque", "fk_departamento") VALUES (15, 'Consertar Impressora', NULL, 2);
INSERT INTO "tb_itemservico"("id", "itemservico", "vinculoestoque", "fk_departamento") VALUES (18, 'Limpar o Chão', NULL, 3);
INSERT INTO "tb_itemservico"("id", "itemservico", "vinculoestoque", "fk_departamento") VALUES (19, 'Trocar Disjuntor', NULL, 4);
INSERT INTO "tb_itemservico"("id", "itemservico", "vinculoestoque", "fk_departamento") VALUES (20, 'Trocar Lampada', NULL, 4);
INSERT INTO "tb_itemservico"("id", "itemservico", "vinculoestoque", "fk_departamento") VALUES (21, 'Trocar Fio elétrico', NULL, 4);
INSERT INTO "tb_itemservico"("id", "itemservico", "vinculoestoque", "fk_departamento") VALUES (22, 'Instalar Tomada', NULL, 4);
INSERT INTO "tb_itemservico"("id", "itemservico", "vinculoestoque", "fk_departamento") VALUES (23, 'Instalar Ponto de luz', NULL, 4);
INSERT INTO "tb_itemservico"("id", "itemservico", "vinculoestoque", "fk_departamento") VALUES (24, 'Trocar Telefone', NULL, 5);
INSERT INTO "tb_itemservico"("id", "itemservico", "vinculoestoque", "fk_departamento") VALUES (25, 'Trocar Tomada RJ 11', NULL, 5);
INSERT INTO "tb_itemservico"("id", "itemservico", "vinculoestoque", "fk_departamento") VALUES (26, 'Trocar Headset', NULL, 5);
INSERT INTO "tb_itemservico"("id", "itemservico", "vinculoestoque", "fk_departamento") VALUES (27, 'Cadastrar novo ramal', NULL, 5);
INSERT INTO "tb_itemservico"("id", "itemservico", "vinculoestoque", "fk_departamento") VALUES (28, 'Instalar Ponto de telefone', NULL, 5);
INSERT INTO "tb_itemservico"("id", "itemservico", "vinculoestoque", "fk_departamento") VALUES (29, 'Configurar WIFI', NULL, 2);
INSERT INTO "tb_itemservico"("id", "itemservico", "vinculoestoque", "fk_departamento") VALUES (30, 'Configurar Rede', NULL, 2);
INSERT INTO "tb_itemservico"("id", "itemservico", "vinculoestoque", "fk_departamento") VALUES (31, 'Formatar Computador', NULL, 2);
INSERT INTO "tb_itemservico"("id", "itemservico", "vinculoestoque", "fk_departamento") VALUES (32, 'Trocar Placa de Rede', NULL, 2);
INSERT INTO "tb_itemservico"("id", "itemservico", "vinculoestoque", "fk_departamento") VALUES (33, 'Crimpar cabo de rede', NULL, 2);
INSERT INTO "tb_itemservico"("id", "itemservico", "vinculoestoque", "fk_departamento") VALUES (36, 'Podar Arvore', NULL, 1);
INSERT INTO "tb_itemservico"("id", "itemservico", "vinculoestoque", "fk_departamento") VALUES (37, 'Aparar a grama', NULL, 1);
