INSERT INTO "tb_tiposervico"("id", "nomeservico", "status", "datacadastro", "fk_prioridade", "fk_departamento") VALUES (16, 'Lâmpada queimada', 't', '2018-10-23 21:00:00', 2, 4);
INSERT INTO "tb_tiposervico"("id", "nomeservico", "status", "datacadastro", "fk_prioridade", "fk_departamento") VALUES (17, 'Disjuntor desarmando', 't', '2018-10-23 21:00:00', 1, 4);
INSERT INTO "tb_tiposervico"("id", "nomeservico", "status", "datacadastro", "fk_prioridade", "fk_departamento") VALUES (18, 'Tomada com problemas', 't', '2018-10-23 21:00:00', 2, 4);
INSERT INTO "tb_tiposervico"("id", "nomeservico", "status", "datacadastro", "fk_prioridade", "fk_departamento") VALUES (20, 'Instalação de tomada', 't', '2018-10-23 21:00:00', 5, 4);
INSERT INTO "tb_tiposervico"("id", "nomeservico", "status", "datacadastro", "fk_prioridade", "fk_departamento") VALUES (19, 'Queda de energia', 't', '2018-10-23 21:00:00', 1, 4);
INSERT INTO "tb_tiposervico"("id", "nomeservico", "status", "datacadastro", "fk_prioridade", "fk_departamento") VALUES (21, 'Monitor com problemas', 't', '2018-10-23 21:00:00', 3, 2);
INSERT INTO "tb_tiposervico"("id", "nomeservico", "status", "datacadastro", "fk_prioridade", "fk_departamento") VALUES (1, 'Instalação Ponto Telefone', 't', '2018-10-23 21:00:00', 5, 5);
INSERT INTO "tb_tiposervico"("id", "nomeservico", "status", "datacadastro", "fk_prioridade", "fk_departamento") VALUES (2, 'Troca de Telefone Fixo', 't', '2018-10-23 21:00:00', 3, 5);
INSERT INTO "tb_tiposervico"("id", "nomeservico", "status", "datacadastro", "fk_prioridade", "fk_departamento") VALUES (3, 'Configuração de Ramal', 't', '2018-10-23 21:00:00', 3, 5);
INSERT INTO "tb_tiposervico"("id", "nomeservico", "status", "datacadastro", "fk_prioridade", "fk_departamento") VALUES (4, 'Troca de Tonner P&B', 't', '2018-10-23 21:00:00', 3, 2);
INSERT INTO "tb_tiposervico"("id", "nomeservico", "status", "datacadastro", "fk_prioridade", "fk_departamento") VALUES (5, 'Troca de Tonner COLORIDO', 't', '2018-10-23 21:00:00', 3, 2);
INSERT INTO "tb_tiposervico"("id", "nomeservico", "status", "datacadastro", "fk_prioridade", "fk_departamento") VALUES (7, 'Falha de acesso a internet', 't', '2018-10-23 21:00:00', 3, 2);
INSERT INTO "tb_tiposervico"("id", "nomeservico", "status", "datacadastro", "fk_prioridade", "fk_departamento") VALUES (8, 'Falha de acesso a Rede', 't', '2018-10-23 21:00:00', 3, 2);
INSERT INTO "tb_tiposervico"("id", "nomeservico", "status", "datacadastro", "fk_prioridade", "fk_departamento") VALUES (9, 'Configurar WIFI', 't', '2018-10-23 21:00:00', 4, 2);
INSERT INTO "tb_tiposervico"("id", "nomeservico", "status", "datacadastro", "fk_prioridade", "fk_departamento") VALUES (10, 'Calçada quebrada', 't', '2018-10-23 21:00:00', 2, 1);
INSERT INTO "tb_tiposervico"("id", "nomeservico", "status", "datacadastro", "fk_prioridade", "fk_departamento") VALUES (11, 'Muro quebrado', 't', '2018-10-23 21:00:00', 2, 1);
INSERT INTO "tb_tiposervico"("id", "nomeservico", "status", "datacadastro", "fk_prioridade", "fk_departamento") VALUES (12, 'Torneira vazando', 't', '2018-10-23 21:00:00', 2, 1);
INSERT INTO "tb_tiposervico"("id", "nomeservico", "status", "datacadastro", "fk_prioridade", "fk_departamento") VALUES (13, 'Bueiro entupido', 't', '2018-10-23 21:00:00', 2, 1);
INSERT INTO "tb_tiposervico"("id", "nomeservico", "status", "datacadastro", "fk_prioridade", "fk_departamento") VALUES (14, 'Podar árvore', 't', '2018-10-23 21:00:00', 4, 1);
INSERT INTO "tb_tiposervico"("id", "nomeservico", "status", "datacadastro", "fk_prioridade", "fk_departamento") VALUES (15, 'Aparar grama', 't', '2018-10-23 21:00:00', 4, 1);
INSERT INTO "tb_tiposervico"("id", "nomeservico", "status", "datacadastro", "fk_prioridade", "fk_departamento") VALUES (6, 'Computador com problemas', 't', '2018-10-23 21:00:00', 2, 2);
